#!/usr/bin/env node
const { argv }             = require("process");
const JSBuild              = require("./js_build");
const CSSBuild             = require("./css_build");
const vfl                  = require("./vfl");

console.log("cdbuild");
console.log("Build tool for Custodesk assets");
console.log();

const PARTS = {
    css: {
        build: CSSBuild.build,
        watch: CSSBuild.watch
    },
    js: {
        build: JSBuild.build,
        watch: JSBuild.watch
    },
};

let g_doWatch = (argv[2] == "--watch") || (argv[2] == "-w");
let g_parts = [];

for (let i = (g_doWatch) ? 3 : 2; i < argv.length; i++)
{
    if (!(argv[i] in PARTS))
    {
        console.log("Invalid part: " + argv[i]);
        console.log("Valid parts: " + Object.keys(PARTS).join(", "));
        return;
    }

    g_parts.push();
}

if (g_parts.length == 0)
{
    g_parts = Object.keys(PARTS);
}

for (const part of g_parts)
{
    console.log(`${g_doWatch ? "Watching" : "Building"} '${part}'...`);
    g_doWatch ? PARTS[part].watch() : PARTS[part].build();
}